### ISSUE TITLE
confCont not found

### ISSUE THREAD

**Issue by RichardScottOZ** [GeoscienceAustralia/MPM-WofE#1]
```R
> calcType <- askforInput("calcType")
Enter calculation type ((a)scending, (d)escending, (c)categorical: confCont <- askforInput("confCont")
> unitArea <- askforInput("unitArea")
Enter unit area (km2): missData <- askforInput("missData")
> 
> calcType <- as.character(calcType)
> confCont <- as.numeric(confCont)
Error: object 'confCont' not found
```

**Comment by RichardScottOZ** [comment]
entirely possible this is user error

I just started having a look using your test example - Calculate Weights - you instruct it to run from Calculate Weights folder in the repository?

**Comment by RichardScottOZ** [comment]
Oh, yes, CalculateWeights

**Comment by Arianne-GA** [comment]
I can't replicate that error.

If you download the data in the TESTDATA folder to your local drive and you are running the "calculate weights" script, set the working directory to the CalculateWeights subfolder to access the relevant test data for that script. When you want to run the "calculate response" script, set the working directory to the CalculateResponse subfolder for the relevant test data for that script.

**Comment by RichardScottOZ** [comment]
Yeah, it is a 'Source with Echo' option selected user error it appears, thanks! :)
